### ISSUE TITLE
Error running main api

### ISSUE THREAD

**Issue by ZhaozhiQIAN** [jsyoon0823/time-series-automl#5]
I got the following error when running `main_api.pi`. I'm using tensorflow 1.15.0.

Traceback (most recent call last):
  File "/home/zq224/WS/time-series-automl/main_api.py", line 75, in <module>
    general_rnn_model, train_y_hat = general_rnn.fit(dataset_training)
  File "/alt/applic/user-maint/zq224/WS/time-series-automl/prediction/general_rnn_module.py", line 153, in fit
    self.model = self.build_model (train_x, train_y)
  File "/alt/applic/user-maint/zq224/WS/time-series-automl/prediction/general_rnn_module.py", line 132, in build_model
    model.compile(loss=binary_cross_entropy_loss, optimizer = 'adam')  
  File "/alt/applic/user-maint/zq224/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/alt/applic/user-maint/zq224/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 373, in compile
    self._compile_weights_loss_and_weighted_metrics()
  File "/alt/applic/user-maint/zq224/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/alt/applic/user-maint/zq224/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1652, in _compile_weights_loss_and_weighted_metrics
    self.total_loss = self._prepare_total_loss(masks)
  File "/alt/applic/user-maint/zq224/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1716, in _prepare_total_loss
    reduction=losses_utils.ReductionV2.NONE)
  File "/alt/applic/user-maint/zq224/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/losses_utils.py", line 107, in compute_weighted_loss
    losses, sample_weight)
  File "/alt/applic/user-maint/zq224/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/losses/util.py", line 148, in scale_losses_by_sample_weight
    sample_weight = weights_broadcast_ops.broadcast_weights(sample_weight, losses)
  File "/alt/applic/user-maint/zq224/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/weights_broadcast_ops.py", line 167, in broadcast_weights
    with ops.control_dependencies((assert_broadcastable(weights, values),)):
  File "/alt/applic/user-maint/zq224/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/weights_broadcast_ops.py", line 103, in assert_broadcastable
    weights_rank_static, values.shape, weights.shape))
ValueError: weights can not be broadcast to values. values.rank=0. weights.rank=2. values.shape=(). weights.shape=(?, 24).

Process finished with exit code 1

**Comment by ZhaozhiQIAN** [comment]
Fixed after using proper loss function.
